---
permalink: deploy/recovery-deployment.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereのセットアップを失ったあとにONTAPが動作している場合は、ONTAPを使用してONTAP tools for VMware vSphereのセットアップをリカバリできます。セットアップが失われたら、セットアップを正常に停止してください。 
---
= ONTAP Tools for VMware vSphereセットアップのリカバリ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereのセットアップを失った場合は、ONTAPボリュームのデータに含まれているデータを使用してONTAP tools for VMware vSphereのセットアップをリカバリできます。セットアップが失われたら、セットアップを正常に停止してください。


NOTE: vCenter ServerまたはONTAPデータ管理ソフトウェアで問題があると、ONTAP tools for VMware vSphereのセットアップをリカバリできません。

* 手順 *

. vSphereサーバにログインします。
. OVAを導入するリソースプール、ノードクラスタ、またはホストに移動します。
. 目的の場所を右クリックし、*[Deploy OVF Template]*を選択します。
. _.ova_fileのURLを入力するか、または_.ova_fileが保存されているフォルダを参照して、*[Next]*を選択します。
+

NOTE: リカバリセットアップのインストールに使用したのと同じOVAビルドを使用する必要があります。

. 仮想マシンの名前とフォルダを選択し、*[Next]*を選択します。
. ホストを選択し、*[次へ]*を選択します。
. テンプレートの概要を確認し、* Next *を選択します。
. ライセンス契約を読んで同意し、* Next *を選択します。
. [設定]ウィンドウで、*[リカバリ]*オプションを選択します。
. [ストレージの選択]*ウィンドウで、構成ファイルとディスクファイルのストレージを選択します。
. [ネットワークの選択]ウィンドウで、各ソースネットワークの宛先ネットワークを選択します。
+

NOTE: ロードバランサのIPアドレスとKubernetes APIサーバのIPアドレスは保持する必要があります。ノードのIPアドレスを変更することも、同じIPアドレスを維持することもできます。

. [テンプレートのカスタマイズ]*>*[システム構成]*ウィンドウを選択します。次の詳細を入力します。
+
.. アプリケーションのユーザ名とパスワード：このユーザ名とパスワードは、VASA ProviderとSRAの両方をvCenter Serverに登録するときに使用します。初期導入時に指定したユーザ名とパスワードとは異なる場合があります。
.. [Enable ASUP]*チェックボックスはデフォルトで選択されています。




AutoSupportを有効または無効にできるのは導入時のみです。..[ASUPプロキシURL]*フィールドに、AutoSupportデータ転送用のファイアウォールブロックを回避するためにこのURLを指定します。..管理者のユーザー名と管理者のパスワード：ONTAPツールマネージャへのログインに使用するパスワードです。初期導入時に指定したユーザ名とパスワードとは異なる場合があります。..[NTP Servers]フィールドにNTPサーバ情報を入力します。..maintenance user password：メンテナンスコンソールのオプションへのアクセスを許可する場合に使用します。です。[テンプレートのカスタマイズ]*>[展開構成]*ウィンドウで、展開時に指定した詳細を入力します。このセクションの値は、データLIFの値を除き、初期導入時に指定した値と同じにする必要があります。


NOTE: リカバリデータが格納されるストレージSVM名は変更しないでください。この環境によってSVMユーザアカウントも直接追加されました。です。HA導入のリカバリの場合は、次の詳細を指定します。コンテンツライブラリの詳細。.. vCenter構成の詳細です。[Customize template]*>[* Node Configuration]*ウィンドウで、リカバリしようとしているセットアップ（非HAまたはHAのセットアップ）に従って詳細を入力します。です。[選択内容の確認]ウィンドウで詳細を確認し、*[終了]*を選択します。

+導入タスクが作成されると、vSphereタスクバーに進行状況が表示されます。です。タスクが完了したら、VMの電源をオンにします。

+インストールが開始されます。インストールの進行状況は、VMのWebコンソールで追跡できます。インストールの一環として、ノード構成が検証されます。OVFフォームの[Customize template]の下のさまざまなセクションで入力された内容が検証されます。不一致がある場合は、修正措置を講じるように求めるダイアログが表示されます。です。ダイアログプロンプトで必要な変更を行います。タブボタンを使用してパネルを移動し、* OK *または*キャンセル*の値を入力します。です。[OK]*または[キャンセル]*を選択すると、指定した値が再度検証されます。ONTAP Tools for VMwareでは、無効な値の修正を3回試行できます。3回試行しても問題を修正できない場合は、製品のインストールが停止し、新しいVMでインストールを試すことを推奨します。です。インストールが完了すると、WebコンソールにONTAP tools for VMware vSphereの状態が表示されます。インストールが完了したら、ページのガイドラインに従ってハードウェア要件を手動で編集する必要があります link:../deploy/sizing-requirements.html["ONTAP Tools for VMware vSphereを導入するための前提条件"] 。
