---
permalink: concepts/ontap-tools-concepts-terms.html 
sidebar: sidebar 
keywords:  
summary: 次のセクションでは、このドキュメントで使用される主な概念と用語について説明します。 
---
= 主要な概念と用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次のセクションでは、このドキュメントで使用される主な概念と用語について説明します。



=== 認証局（CA）

CAは、Secure Sockets Layer（SSL）証明書を発行する信頼されたエンティティです。



=== デュアルスタック

デュアルスタックネットワークは、IPv4アドレスとIPv6アドレスの両方の同時使用をサポートするネットワーク環境です。



=== 高可用性（ HA ）

クラスタノードは、ノンストップオペレーションを実現するためにHAペアで構成されます。



=== 論理ユニット番号（LUN）

LUNは、Storage Area Network（SAN；ストレージエリアネットワーク）内の論理ユニットを識別するために使用される番号です。これらのアドレス指定可能なデバイスは、通常、SCSI（Small Computer System Interface）プロトコルまたはそのカプセル化された派生物の1つを介してアクセスされる論理ディスクです。



=== ONTAPツールマネージャ

ONTAP tools Managerを使用すると、管理対象のvCenter Serverインスタンスやオンボードストレージバックエンドに対して、VMware vSphere管理者向けのONTAP toolsをより細かく制御できます。ONTAP Tools Mangerを使用すると、vCenter Serverインスタンス、ストレージバックエンド、証明書、パスワード、ログバンドルのダウンロードを管理できます。



=== Open Virtual Appliance（OVA；オープン仮想アプライアンス）

OVAは、仮想マシン上で実行する必要がある仮想アプライアンスまたはソフトウェアをパッケージ化して配布するためのオープンスタンダードです。



=== SnapMirrorアクティブ（SMAS）

SnapMirror Active Syncを使用すると、サイト全体に障害が発生してもビジネスサービスの運用を継続できるため、アプリケーションをセカンダリコピーを使用して透過的にフェイルオーバーできます。SnapMirror Active Syncでフェイルオーバーをトリガーするには、手動操作やカスタムスクリプトが必要です。



=== Storage Replication Adapter（SRA）

SRAは、SRMアプライアンスにインストールされるストレージベンダー固有のソフトウェアです。このアダプタを使用すると、Storage Virtual Machine（SVM）レベルおよびクラスタレベルの設定でSite Recovery Managerとストレージコントローラの間の通信が可能になります。



=== Storage Virtual Machine（SVM）

SVMは、ハイパーバイザーで実行される仮想マシンと同様に、物理リソースを抽象化する論理エンティティです。SVMには、複数のデータボリュームと、クライアントへのデータの提供に使用するLIFが1つ以上含まれます。



=== Virtual Machine File System（VMFS）

VMFSは、VMware vSphere環境に仮想マシンファイルを格納するために特別に設計されたクラスタファイルシステムです。



=== 仮想ボリューム（ VVOL ）

VVOLは、仮想マシンで使用されるストレージをボリュームレベルで抽象化します。これにはいくつかの利点があり、従来のLUNを使用する代わりに使用できます。VVOLデータストアは、通常、VVOLのコンテナとして機能する単一のLUNに関連付けられます。



=== VMストレージポリシー

仮想マシンストレージポリシーは、vCenter Serverの[Policies and Profiles]に作成されます。VVOLの場合は、NetApp VVOLストレージタイププロバイダのルールを使用してルールセットを作成します。



=== VMware Site Recovery Manager（SRM）

SRMは、VMware仮想環境のビジネス継続性、ディザスタリカバリ、サイト移行、および無停止テスト機能を提供します。



=== VMware vSphere APIs for Storage Awareness（VASA）

VASAは、管理用のストレージアレイとvCenter Serverを統合する一連のAPIです。このアーキテクチャは、VMware vSphereとストレージシステムの間の通信を処理するVASA Providerなど、複数のコンポーネントに基づいています。



=== VMware vSphere Storage APIs - Array Integration（VAAI）

VAAIは、VMware vSphere ESXiホストとストレージデバイスの間の通信を可能にする一連のAPIです。APIには、ストレージ処理をアレイにオフロードするためにホストが使用する一連のプリミティブ処理が含まれています。VAAIは、ストレージを大量に消費するタスクのパフォーマンスを大幅に向上させることができます。



=== vVolデータストア

vVolデータストアは、VASA Providerで作成および管理されるvVolコンテナを表す論理データストアです。



=== RPOゼロ

RPOはRecovery Point Objective（目標復旧時点）の略で、所定の時間内に許容可能とみなされるデータ損失量です。RPOがゼロの場合は、データ損失が許容されないことを意味します。
