---
permalink: configure/create-vvols-datastore.html 
sidebar: sidebar 
keywords:  
summary: vVolデータストアは、新しいボリュームまたは既存のボリュームを使用して作成できます。既存のボリュームと新しいボリュームを組み合わせてvVolデータストアを作成することもできます。 
---
= データストアを作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストクラスタレベルでデータストアを作成すると、データストアが作成されてデスティネーションのすべてのホストにマウントされます。この操作は、現在のユーザに実行権限がある場合にのみ有効になります。

[Create Datastore]アクションウィザードでは、NFS、VMFS、およびvVolデータストアを作成できます。



== vVolデータストアを作成する

vVolデータストアは、新しいボリュームまたは既存のボリュームを使用して作成できます。既存のボリュームと新しいボリュームが混在しているvVolデータストアを作成することはできません。


NOTE: ルートアグリゲートがSVMにマッピングされていないことを確認します。

.開始する前に
選択したvCenterにVASA Providerが登録されていることを確認してください。

.手順
. 次のコマンドを使用してvSphere Clientにログインします。 `\https://vcenterip/ui`
. ホストシステム、ホストクラスタ、データセンターを右クリックし、* NetApp ONTAP tools *>*[Create Datastore]*を選択します。
. [タイプ]*ペインで、*[データストアタイプ]*で[VVols]を選択します。
. [名前とプロトコル]ペインで、*[データストア名]*と*[プロトコル]*の情報を指定します。
. [ストレージ]*ペインで、*[プラットフォーム]*および*[Storage VM]*を選択します。[アドバンストオプション]*セクションで、カスタムのエクスポートポリシー（NFSプロトコルの場合）またはカスタムのイニシエータグループ名（iSCSIプロトコルの場合）を必要に応じて選択します。
+
** [プラットフォーム]オプションと[非対称]オプションを使用すると、[SVM]ドロップダウンオプションをフィルタして除外できます。作成するSVMを選択するか、ボリュームをデータストアの作成に使用してください。
** [非対称]*トグルボタンは、前の手順で[iSCSI]を選択し、[プラットフォーム]ドロップダウンで[パフォーマンス]または[容量]を選択した場合にのみ表示されます。
** AFFプラットフォームの場合は[非対称]トグルボタンを選択し、ASAプラットフォームの場合は無効にします。


. [ストレージ属性]*ペインで、新しいボリュームを作成するか、既存のボリュームを使用できます。新しいボリュームを作成するときに、データストアでQoSを有効にすることができます。
. [サマリ]*ペインで選択内容を確認し、*[完了]*をクリックします。vVolデータストアが作成され、すべてのホストにマウントされます。




== NFSデータストアを作成する

VMware Network File System（NFS）データストアは、NFSプロトコルを使用して、ESXiホストをネットワーク経由で共有ストレージデバイスに接続します。NFSデータストアはVMware vSphere環境で一般的に使用され、シンプルさや柔軟性など、いくつかの利点があります。

.手順
. 次のコマンドを使用してvSphere Clientにログインします。 `\https://vcenterip/ui`
. ホストシステム、ホストクラスタ、またはデータセンターを右クリックし、* NetApp ONTAP tools *>*[Create Datastore]*を選択します。
. [タイプ]ペインで、*[データストアタイプ]*で[NFS]を選択します。
. [名前とプロトコル]*ペインで、データストア名、サイズ、およびプロトコル情報を入力します。アドバンストオプションで、*[データストアクラスタ]*および*[Kerberos認証]*を選択します。
+

NOTE: Kerberos認証は、NFS 4.1プロトコルが選択されている場合にのみ使用できます。

. [ストレージ]*ペインで、*[プラットフォーム]*および*[Storage VM]*を選択します。[アドバンストオプション]*セクションで*[カスタムエクスポートポリシー]*を選択できます。
+
** *非対称*トグルボタンは、プラットフォームのドロップダウンでパフォーマンスまたは容量が選択されている場合にのみ表示されます。
** *[プラットフォーム]ドロップダウンの[任意]*オプションを使用すると、プラットフォームフラグまたは非対称フラグに関係なく、vCenterに含まれるすべてのSVMを表示できます。


. [ストレージ属性]*ペインで、ボリュームを作成するアグリゲートを選択します。アドバンストオプションで、必要に応じて*[スペースリザベーション]*および*[QoSを有効にする]*を選択します。
. [概要]*ペインで選択内容を確認し、*[完了]*をクリックします。


NFSデータストアが作成され、すべてのホストにマウントされます。



== VMFSデータストアの作成

Virtual Machine File System（VMFS）は、VMware vSphere環境に仮想マシンファイルを格納するために特別に設計されたクラスタファイルシステムです。複数のESXiホストが同じ仮想マシンファイルに同時にアクセスできるため、vMotionや高可用性などの機能が有効になります。

.手順
. 次のコマンドを使用してvSphere Clientにログインします。 `\https://vcenterip/ui`
. ホストシステム、ホストクラスタ、またはデータストアを右クリックし、* NetApp ONTAP tools *>*[Create Datastore]*を選択します。
. [タイプ]ペインで、*[データストアタイプ]*で[VMFS]を選択します。
. [名前とプロトコル]*ペインで、データストア名、サイズ、およびプロトコルの情報を入力します。ペインの*[アドバンストオプション]*セクションで、このデータストアを追加するデータストアクラスタを選択します。
. [ストレージ]ペインで[プラットフォームとStorage VM]を選択します。[非対称]トグルボタンを選択します。ペインの*[アドバンストオプション]*セクションで*[カスタムイニシエータグループ名]*を指定します（オプション）。データストア用に既存のigroupを選択するか、カスタム名を指定して新しいigroupを作成できます。
+
プラットフォームのドロップダウンで*[いずれか]*オプションを選択すると、プラットフォームフラグまたは非対称フラグに関係なく、vCenterに含まれるすべてのSVMが表示されます。

. ストレージ属性ペインで、ドロップダウンメニューから*[アグリゲート]*を選択します。必要に応じて*[アドバンストオプション]*セクションで*[スペースリザベーション]*、*[既存のボリュームを使用]*、*[QoSを有効にする]*オプションを選択し、必要に応じて詳細を指定します。
. [概要]*ペインでデータストアの詳細を確認し、*[終了]*をクリックします。VMFSデータストアが作成され、すべてのホストにマウントされます。

